version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - TPA_AUTHORIZATION_HEADER=${TPA_AUTHORIZATION_HEADER}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - PINECONE_API_KEY=${PINECONE_API_KEY}
      # - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      # - PINECONE_INDEX=${PINECONE_INDEX}
 